version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile  # Убедитесь, что Dockerfile существует в той же папке
    ports:
      - "5000:8080"            # Пробрасываем порт 80 контейнера на порт 5000 хоста
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    volumes:
      - ./:/app              # Монтирование кода (для разработки, можно удалить в продакшене)
