name: Test and Build

on:
  push:  # запускается для всех веток кроме main
    branches-ignore: [ 'main' ]

jobs:
  test-and-build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests
      run: dotnet test --no-restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
