name: Test and Build

on:
  push:  # запускается для всех веток кроме main
    branches: 
      - main
      - dev
      - feature/*
  pull_request:
    branches:
      - main
      - dev
      - feature/*

jobs:
  test-and-build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Run tests
      run: dotnet test --no-restore
      
    - name: Debug info
      run: |
       echo "Branch: ${{ github.ref }}"
       echo "Event: ${{ github.event_name }}"
       ls -la  # Проверить содержимое рабочей директории
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
